version: "2" # not sure what podman supports now, but no need for fancy 3.x features

services:
  tornado-api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    ports:
      - "8888:8888"  # 80 and 443 later
    environment:
      - "ADDRESS_CACHE=redis"
    stop_grace_period: 1s
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    environment:
      - "ADDRESS_CACHE=redis"
    devices:
      - "/dev/video0:/dev/video0"  # TODO make loading dynamic
      - "/dev/video1:/dev/video1"  # FIXME is *1 ever needed?
  redis:
    image: "redis:alpine"
