FROM python:3-slim-bullseye
RUN apt-get update \
    && apt-get install -y \
        libgl1 \
        libglib2.0-0 \
    && apt-get clean
RUN pip install --no-cache \
    opencv-python \
    redis
COPY src/backend /opt/backend
WORKDIR /opt/backend
ENTRYPOINT ["python3", "-u", "backend.py"]
